begin;
select plan(19);
create temp table offline_ids as select gen_random_uuid() owner,gen_random_uuid() event,gen_random_uuid() device,gen_random_uuid() product;
insert into auth.users(id,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,aud,role) select owner,'offline-sql@nireq.local','x',now(),'{}','{}','authenticated','authenticated' from offline_ids;
insert into public.artists(id,email,slug,display_name,is_verified,is_public,published_at) select owner,'offline-sql@nireq.local','offline-sql','Offline',true,true,now() from offline_ids;
insert into public.events(id,artist_id,event_name,start_date,end_date,status,is_booth_open) select event,owner,'Offline',now()-interval '1 hour',now()+interval '1 day','Confirmed',true from offline_ids;
insert into public.products(id,artist_id,name,price,stock_total,is_unlimited) select product,owner,'Item',100,10,false from offline_ids;
select set_config('request.jwt.claims',json_build_object('sub',owner,'email','offline-sql@nireq.local','role','authenticated')::text,true) from offline_ids;
select lives_ok($$select public.prepare_offline_device(event,device) from offline_ids$$,'authorized owner prepares primary');
select throws_ok($$select public.prepare_offline_device(event,gen_random_uuid()) from offline_ids$$,'P0001','another_primary_device','second device cannot become primary');
select is((select public.queue_updates_delayed(event) from offline_ids),false,'fresh primary has no outage');
update public.offline_devices set heartbeat_at=now()-interval '2 minutes' where event_id=(select event from offline_ids);
select is((select public.queue_updates_delayed(event) from offline_ids),true,'missed heartbeat pauses expiry');
select public.offline_device_heartbeat(event,device,false) from offline_ids;
select is((select public.queue_updates_delayed(event) from offline_ids),true,'reconnect provides grace');
create temp table offline_payload as select gen_random_uuid() id,jsonb_build_object('kind','sale','items',jsonb_build_array(jsonb_build_object('product_id',product,'quantity',2)),'collected_total',200,'method','cash') payload from offline_ids;
select is((select public.apply_offline_operation(p.id,i.event,i.device,p.payload)->>'status' from offline_ids i,offline_payload p),'applied','receipt applies');
select is((select public.apply_offline_operation(p.id,i.event,i.device,p.payload)->>'status' from offline_ids i,offline_payload p),'applied','same receipt retry returns original');
select is((select stock_sold from public.products where id=(select product from offline_ids)),2,'retry sells stock once');
select is((select public.apply_offline_operation(gen_random_uuid(),i.event,i.device,jsonb_set(p.payload,'{collected_total}','150'))->>'status' from offline_ids i,offline_payload p),'conflict','changed actual amount retains conflict');
select is((select stock_sold from public.products where id=(select product from offline_ids)),2,'conflict rolls back stock');
insert into public.queues(artist_id,event_id,queue_number,queue_service_date,status,called_at)
select owner,event,1,current_date,'calling',now()-interval '1 hour' from offline_ids;
update public.queues set status='expired' where event_id=(select event from offline_ids);
select is((select status from public.queues where event_id=(select event from offline_ids)),'calling','expiry is suppressed during reconnect grace');
select throws_ok($$select public.resolve_offline_operation((select id from public.offline_operations where status='conflict' and event_id=(select event from offline_ids)),(select id from public.orders where event_id=(select event from offline_ids) limit 1),'Checked receipt')$$,'P0001','receipt_does_not_match','cannot resolve against a different amount');
update public.products set price=75 where id=(select product from offline_ids);
create temp table reconciled_order as select public.create_walkin_order_with_stock(event,jsonb_build_array(jsonb_build_object('product_id',product,'quantity',2)),'cash',gen_random_uuid()) id from offline_ids;
select lives_ok($$select public.resolve_offline_operation((select id from public.offline_operations where status='conflict' and event_id=(select event from offline_ids)),(select id from reconciled_order),'Correct receipt recorded without collecting again')$$,'management links matching sale');
select is((select stock_sold from public.products where id=(select product from offline_ids)),4,'reconciliation does not deduct stock again');
create temp table offline_staff as select gen_random_uuid() id;
insert into auth.users(id,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,aud,role) select id,'offline-staff@nireq.local','x',now(),'{}','{}','authenticated','authenticated' from offline_staff;
insert into public.artist_members(artist_id,member_email,role,status) select owner,'offline-staff@nireq.local','queue_staff','active' from offline_ids;
select set_config('request.jwt.claims',json_build_object('sub',id,'email','offline-staff@nireq.local','role','authenticated')::text,true) from offline_staff;
select throws_ok($$select public.prepare_offline_device(event,gen_random_uuid()) from offline_ids$$,'P0001','forbidden','queue staff cannot prepare offline writes');
select set_config('request.jwt.claims',json_build_object('sub',owner,'email','offline-sql@nireq.local','role','authenticated')::text,true) from offline_ids;
update public.offline_devices set resume_after=now()-interval '1 minute' where event_id=(select event from offline_ids);
select lives_ok($$select public.prepare_offline_device(event,gen_random_uuid(),true) from offline_ids$$,'owner can explicitly replace primary');
select is((select public.queue_updates_delayed(event) from offline_ids),true,'replacement preserves a grace period');
select is((select public.apply_offline_operation(gen_random_uuid(),i.event,i.device,p.payload)->>'reason' from offline_ids i,offline_payload p),'another_primary_device','old device receipt is quarantined after replacement');
select set_config('request.jwt.claims','{"role":"anon"}',true);
select throws_ok($$select public.apply_offline_operation(gen_random_uuid(),event,device,'{"kind":"sale"}') from offline_ids$$,'P0001','forbidden','anonymous cannot submit offline operations');
select * from finish();
rollback;
