import type { Language } from "../i18n";

const thai: Record<string, string> = {
  "Loading pre-order dashboard...": "กำลังโหลดออเดอร์...",
  "Reject reason (sent to the customer)": "เหตุผลที่ไม่รับสลิป (แจ้งให้ลูกค้าเห็น)",
  "Example: Transfer amount does not match, duplicate slip, or payment not found.": "เช่น ยอดโอนไม่ตรง สลิปซ้ำ หรือไม่พบเงินเข้า",
  "Tracking number": "เลขติดตามพัสดุ",
  "Carrier (e.g. Kerry, Flash, ไปรษณีย์ไทย)": "ขนส่ง เช่น Flash หรือไปรษณีย์ไทย",
  "Carrier": "ขนส่ง",
  "Reject": "ไม่รับสลิป",
  "Confirm": "ยืนยัน",
  "Refresh": "โหลดใหม่",
  "Export CSV": "ดาวน์โหลด CSV",
  "Customers pay the creator directly. Nireq stores private evidence for your review; you decide whether to confirm or reject it.": "ลูกค้าโอนเงินเข้าบัญชีของคุณโดยตรง ตรวจยอดเงินจริงก่อนยืนยันสลิป",
  "Order saved · email not sent": "บันทึกออเดอร์แล้ว แต่ส่งอีเมลไม่สำเร็จ",
  "Retry only sends the email for": "ลองส่งอีเมลอีกครั้งสำหรับ",
  "; it does not repeat payment, stock, or fulfillment changes.": "โดยไม่ยืนยันเงิน ตัดสต็อก หรือส่งมอบซ้ำ",
  "Order status filters": "กรองสถานะออเดอร์",
  "Search code, name, contact, product": "ค้นหารหัส ชื่อ ช่องทางติดต่อ หรือสินค้า",
  "Search orders": "ค้นหาออเดอร์",
  "Post · ship": "หลังงาน · จัดส่ง",
  "Ship to:": "ส่งถึง:",
  "Shipped ·": "ส่งแล้ว ·",
  "Reason:": "เหตุผล:",
  "Mark shipped": "ยืนยันจัดส่ง",
  "Expected revenue": "ยอดรอและยืนยันรวม",
  "Confirmed revenue": "ยอดยืนยันแล้ว",
  "Production Summary": "สรุปสินค้าที่ต้องเตรียม",
  "No submitted or confirmed pre-orders yet.": "ยังไม่มีออเดอร์ที่ส่งสลิปหรือยืนยันแล้ว",
  "Product": "สินค้า",
  "Needs review": "รอตรวจสลิป",
  "To prepare": "ต้องเตรียม",
  "Expected": "ยอดรวม",
  "Post-order Dashboard": "ออเดอร์หลังงาน",
  "Pre-order Dashboard": "ออเดอร์ก่อนงาน",
  "Review transfers, then ship orders": "ตรวจยอดโอน แล้วจัดส่งสินค้า",
  "Review transfers, then prepare production": "ตรวจยอดโอน แล้วเตรียมสินค้า",
  "Sending…": "กำลังส่ง…",
  "Retry email": "ส่งอีเมลอีกครั้ง",
  "Awaiting payment": "รอชำระเงิน",
  "Rejected": "ไม่รับสลิป",
  "Expired": "หมดเวลา",
  "To ship": "รอจัดส่ง",
  "Rejected / expired": "ไม่รับ / หมดเวลา",
  "All orders": "ทุกออเดอร์",
  "View slip": "ดูสลิป",
  "No orders match this filter.": "ไม่พบออเดอร์ที่ตรงกับตัวกรอง",
  "View evidence": "ดูหลักฐาน",
  "No evidence": "ยังไม่มีหลักฐาน",
  "Event": "อีเวนต์",
  "Order Settings": "ช่วงขายและรับเงิน",
  "Set event details, sales schedule, pickup notes, and payment instructions in one place.": "ตั้งช่วงขายก่อนงานและหลังงาน พร้อมวิธีชำระเงินและคำแนะนำรับสินค้า แล้วบันทึกก่อนออกจากหน้านี้",
  "Event details": "รายละเอียดงาน",
  "Basic information used across the customer page, queue, POS, and order flows.": "ข้อมูลนี้แสดงให้ลูกค้าและทีมงานเห็นตรงกัน ทั้งหน้าร้าน คิว และการขาย",
  "Event name": "ชื่องาน",
  "Event starts": "วันและเวลาเริ่มงาน",
  "Event ends": "วันและเวลาจบงาน",
  "Location": "สถานที่",
  "Booth detail": "ตำแหน่งบูธ",
  "Queueing area": "จุดเข้าคิว",
  "Entrance fee": "ค่าเข้างาน",
  "Transit info": "การเดินทาง",
  "e.g. Siam Paragon": "เช่น สยามพารากอน",
  "e.g. A12, Creator Hall": "เช่น บูธ A12 โซนครีเอเตอร์",
  "e.g. Queue lane beside booth A12": "เช่น ช่องเข้าคิวข้างบูธ A12",
  "e.g. Free / 300 THB": "เช่น เข้าฟรี / 300 บาท",
  "How customers should get to the venue.": "แนะนำวิธีเดินทางมายังสถานที่จัดงาน",
  "Sales schedule": "ช่วงเปิดขาย",
  "Live event day": "ขายในวันงาน",
  "Auto-active from event start to end.": "ใช้ช่วงวันและเวลาเริ่ม–จบงานที่กำหนดไว้",
  "Pre-order": "สั่งก่อนงาน",
  "Post-order": "สั่งหลังงาน",
  "Reserve before event, pickup at booth.": "เปิดให้สั่งก่อนงาน แล้วมารับที่บูธ",
  "Order after event, fulfill later.": "เปิดรับออเดอร์ต่อหลังงาน แล้วส่งมอบภายหลัง",
  "Emergency close customer ordering": "ระงับรับออเดอร์ลูกค้า",
  "Use only when customers should not place new orders even if a schedule window is open.": "ใช้เมื่อจำเป็นต้องหยุดรับออเดอร์ใหม่ แม้ยังอยู่ในช่วงเปิดขาย",
  "Pre-order window": "ช่วงสั่งก่อนงาน",
  "Customers can reserve items before the event, then pick them up at the booth.": "ลูกค้าสั่งสินค้าก่อนวันงาน แล้วมารับสินค้าที่บูธตามคำแนะนำของคุณ",
  "Pre-order opens": "เริ่มรับออเดอร์ก่อนงาน",
  "Pre-order closes": "ปิดรับออเดอร์ก่อนงาน",
  "Post-order window": "ช่วงสั่งหลังงาน",
  "Post-order opens": "เริ่มรับออเดอร์หลังงาน",
  "Post-order closes": "ปิดรับออเดอร์หลังงาน",
  "Times are saved using the event timezone:": "วันเวลาอ้างอิงเขตเวลาของงาน:",
  "Pickup instructions": "คำแนะนำรับสินค้า",
  "Example: Show your pickup code at booth A12 between 12:00-17:00.": "เช่น แสดงรหัสรับสินค้าที่บูธ A12 เวลา 12:00–17:00 น.",
  "Payment instructions": "วิธีชำระเงิน",
  "Money goes directly to your account. NireQ only stores the instruction and slip workflow.": "ลูกค้าโอนเงินเข้าบัญชีของคุณโดยตรง และส่งสลิปให้คุณตรวจผ่าน NireQ",
  "Enabled": "เปิดใช้งาน",
  "Auto": "ตามเวลางาน",
  "Method type": "วิธีรับเงิน",
  "Bank transfer": "โอนผ่านธนาคาร",
  "QR image": "รูป QR รับเงิน",
  "Other": "อื่น ๆ",
  "Display name": "ชื่อวิธีชำระเงินที่ลูกค้าเห็น",
  "PromptPay ID": "หมายเลขพร้อมเพย์",
  "Phone / national ID / e-wallet ID": "เบอร์โทร / เลขประจำตัว / หมายเลขกระเป๋าเงิน",
  "Payment deadline": "กำหนดชำระเงิน",
  "Bank name": "ธนาคาร",
  "Account name": "ชื่อบัญชี",
  "Account number": "เลขบัญชี",
  "Account holder": "ชื่อเจ้าของบัญชี",
  "Payment QR image": "รูป QR ชำระเงิน",
  "Payment QR preview": "ตัวอย่าง QR ชำระเงิน",
  "Replace image": "เปลี่ยนรูป",
  "Remove": "นำออก",
  "Uploading…": "กำลังอัปโหลด…",
  "Upload PromptPay / transfer QR image": "อัปโหลด QR รับเงิน",
  "Extra instructions": "คำแนะนำเพิ่มเติม",
  "Example: Transfer exact amount, upload slip, then wait for confirmation.": "เช่น โอนตามยอดที่แจ้ง แนบสลิป แล้วรอร้านยืนยัน",
  "Event catalog": "สินค้าและสต็อกของงาน",
  "Saving...": "กำลังบันทึก...",
  "Save settings": "บันทึกการตั้งค่า",
  "Readiness checklist": "ตรวจความพร้อม",
  "Ready": "พร้อม",
  "Check": "ต้องตรวจ",
  "Configure": "ตั้งค่า",
  "Event catalog has products": "เลือกสินค้าเข้าร่วมงาน",
  "Add products to this event catalog before opening customer orders.": "เพิ่มสินค้าเข้าร่วมงานก่อนเปิดรับออเดอร์",
  "Finite stock is available": "มีสต็อกพร้อมขาย",
  "All event products are unlimited.": "สินค้าทุกรายการในงานไม่จำกัดจำนวน",
  "Emergency close is on": "กำลังระงับรับออเดอร์",
  "Customer ordering is manually closed until you turn this off.": "ลูกค้ายังสั่งไม่ได้จนกว่าจะยกเลิกการระงับรับออเดอร์",
  "Pre-order window is valid": "ช่วงสั่งก่อนงานถูกต้อง",
  "Open and close times are ready.": "กำหนดเวลาเปิดและปิดครบแล้ว",
  "Set a pre-order window that closes before the event starts.": "ตั้งเวลาปิดรับออเดอร์ให้ก่อนเวลาเริ่มงาน",
  "Pre-order closes before event": "ปิดรับออเดอร์ก่อนเริ่มงาน",
  "Pre-order ends before event-day live sales begin.": "ปิดสั่งก่อนงานแล้วจึงเริ่มขายในวันงาน",
  "Move the pre-order close time before the event starts.": "เลื่อนเวลาปิดรับออเดอร์ให้ก่อนเริ่มงาน",
  "Post-order window is valid": "ช่วงสั่งหลังงานถูกต้อง",
  "Set a post-order window that starts after the event ends.": "ตั้งเวลาเริ่มสั่งหลังงานให้หลังเวลาจบงาน",
  "Post-order starts after event": "เริ่มสั่งหลังจบงาน",
  "Pickup instructions added": "มีคำแนะนำรับสินค้า",
  "Customers will see pickup instructions after ordering.": "ลูกค้าเห็นคำแนะนำรับสินค้าหลังสั่งซื้อ",
  "Tell customers where and when to show their pickup code.": "ระบุสถานที่และเวลาที่ลูกค้าต้องแสดงรหัสรับสินค้า",
  "Payment instructions added": "มีวิธีชำระเงิน",
  "Customers can see how to transfer before uploading a slip.": "ลูกค้าเห็นวิธีโอนเงินก่อนแนบสลิป",
  "Add PromptPay, bank account, QR image, or clear payment instructions.": "เพิ่มพร้อมเพย์ บัญชีธนาคาร รูป QR หรือคำแนะนำการชำระเงิน",
  "Event Dashboard": "ยอดขายของงาน",
  "Order History": "ประวัติการขาย",
  "Back to event workspace": "กลับไปเตรียมงาน",
  "Export summary": "ดาวน์โหลดสรุป",
  "Net Revenue": "ยอดขายสุทธิ",
  "Total Revenue": "ยอดขายสุทธิ",
  "Discount Given": "ส่วนลดที่ให้",
  "Items Sold": "จำนวนชิ้นที่ขาย",
  "Queue Conversion": "คิวที่สำเร็จ",
  "Active Queue": "คิวที่กำลังดำเนินการ",
  "Avg Wait": "เวลารอเฉลี่ย",
  "Avg Service": "เวลาให้บริการเฉลี่ย",
  "Payment Mix": "สัดส่วนวิธีชำระเงิน",
  "Cash / Transfer orders": "ออเดอร์เงินสด / โอนเงิน",
  "Pre-order Revenue": "ยอดขายก่อนงาน",
  "Awaiting Pickup": "รอรับสินค้า",
  "reserved stock still held": "ยังมีสต็อกจองไว้",
  "Live Queue Revenue": "ยอดขายจากคิว",
  "Walk-in Revenue": "ยอดขายหน้าบูธ",
  "What To Watch Next": "ข้อสังเกตจากยอดขาย",
  "Cash": "เงินสด",
  "Transfer": "โอนเงิน",
  "Product Sales": "ยอดขายสินค้า",
  "No sales yet": "ยังไม่มียอดขาย",
  "Transactions": "รายการขาย",
  "Date & Time": "วันและเวลา",
  "Customer": "ลูกค้า",
  "Items": "สินค้า",
  "Amount": "ยอดเงิน",
  "Method": "การชำระเงิน",
  "Walk-in": "หน้าบูธ",
  "No transactions found for this event.": "ไม่พบรายการขายในช่วงที่เลือก",
  "Loading history...": "กำลังโหลดประวัติ...",
  "Loading event dashboard...": "กำลังโหลดยอดขาย...",
  "Event not found.": "ไม่พบอีเวนต์",
  "Category Performance": "ยอดขายตามหมวดหมู่",
  "Hourly Sales": "ยอดขายรายชั่วโมง",
  "Payment Methods": "วิธีชำระเงิน",
  "Revenue": "ยอดขาย",
  "Orders": "ออเดอร์",
  "Queue": "คิว",
  "Selling": "เปิดขาย",
  "Booth open": "บูธเปิด",
  "Booth closed": "บูธปิด",
  "Prep": "เตรียมงาน",
  "Closed": "ยังไม่เปิดขาย",
  "Setup": "ตั้งค่า",
  "Before sales open": "รายละเอียดการเตรียมงาน",
  "Setup Event": "รายละเอียดและช่วงขาย",
  "Setup Product": "สินค้าและโปรโมชัน",
  "Event Catalog": "สินค้าและสต็อก",
  "Event Promotion": "โปรโมชันของงาน",
  "Event details and order timing.": "วันเวลา สถานที่ และช่วงรับออเดอร์",
  "Products, event stock, and event-only offers.": "เลือกสินค้า จัดสรรสต็อก และกำหนดโปรโมชันสำหรับงาน",
  "Date and location are set": "มีวันเวลาและสถานที่แล้ว",
  "Confirm date, location, and booth detail": "ตรวจวันเวลา สถานที่ และตำแหน่งบูธ",
  "Customer handoff notes are set": "มีคำแนะนำรับสินค้าแล้ว",
  "Add pickup notes when this event needs pickup flow": "เพิ่มคำแนะนำเมื่อต้องให้ลูกค้ามารับสินค้า",
  "Choose products and event stock": "เลือกสินค้าและกำหนดสต็อกของงาน",
  "Optional event-only price rules": "เลือกใช้ส่วนลดหรือของแถม ไม่จำเป็นต้องมีโปรโมชัน",
  "Live event-day sales are automatic": "ขายวันงานตามช่วงเวลางาน",
  "Optional": "ไม่บังคับ",
  "Needs setup": "ต้องตั้งค่า",
  "Now": "ขณะนี้",
  "Loading order settings...": "กำลังโหลดการตั้งค่า...",
  "Back to events": "กลับไปดูอีเวนต์",
  "Event not found or unavailable.": "ไม่พบอีเวนต์หรือไม่สามารถเปิดได้",
  "ready": "ข้อที่พร้อม",
  "Live queue / POS is automatic during the event day. Turn on pre-order or post-order when this event needs customer orders outside the live booth.": "ขายหน้าบูธและจัดการคิวได้ในช่วงวันงาน เปิดตัวเลือกด้านล่างหากต้องการรับออเดอร์ก่อนงานหรือหลังงานด้วย",
  "Customers can order after the event, then you fulfill by shipping or post-event handling.": "ลูกค้าสั่งหลังจบงาน คุณส่งมอบสินค้าตามคำแนะนำที่แจ้งไว้",
  "Loading event workspace...": "กำลังโหลดอีเวนต์...",
  "Event workspace unavailable": "ไม่สามารถเปิดอีเวนต์ได้",
  "Booth": "บูธ",
  "No workspace actions are available for your role.": "บทบาทของคุณยังไม่มีสิทธิ์ดำเนินการในหน้านี้",
  "Event timeline": "ช่วงการขายของงาน",
  "Progress at a glance": "สถานะการดำเนินงาน",
  "Attention": "รายการที่ต้องดูแล",
  "Needs action": "ต้องดำเนินการ",
  "No urgent items": "ไม่มีรายการเร่งด่วน",
  "Use the event tabs when you need deeper setup, sales, or order details.": "เลือกเมนูของงานเพื่อดูรายละเอียดสินค้า ยอดขาย และออเดอร์",
  "Edit Event": "แก้ไขรายละเอียดงาน",
  "Event timing": "วันเวลาและเขตเวลาของงาน",
  "Queue days reset using this event timezone, so choose the timezone where the booth is actually running.": "ระบบเริ่มเลขคิวของแต่ละวันตามเขตเวลานี้ เลือกให้ตรงกับสถานที่จัดงาน",
  "Status": "สถานะ",
  "Confirmed": "ยืนยันจัดงาน",
  "Cancelled": "ยกเลิก",
  "Ended": "จบงานแล้ว",
  "Event Name *": "ชื่องาน *",
  "Time Zone *": "เขตเวลา *",
  "Used for end-of-day and daily queue reset.": "ใช้กำหนดวันสิ้นสุดและเริ่มเลขคิวของแต่ละวัน",
  "Start Date *": "วันเริ่มงาน *",
  "End Date *": "วันจบงาน *",
  "Booth Detail": "ตำแหน่งบูธ",
  "Queueing Area": "จุดเข้าคิว",
  "Entrance Fee": "ค่าเข้างาน",
  "Transit Info": "การเดินทาง",
  "Cancel": "ยกเลิก",
  "Payment Summary": "สรุปการรับเงิน",
  "Pink segment shows cash revenue share. Remaining share is transfer.": "สีชมพูแสดงสัดส่วนยอดเงินสด ส่วนที่เหลือเป็นยอดโอนเงิน",
  "Sales By Category": "ยอดขายตามหมวดหมู่",
  "No category sales yet.": "ยังไม่มียอดขายตามหมวดหมู่",
  "sold": "ชิ้นที่ขาย",
  "Top Products": "สินค้าขายดี",
  "No product sales yet.": "ยังไม่มียอดขายสินค้า",
  "Hourly Sales Trend": "ยอดขายรายชั่วโมง",
  "No hourly sales yet.": "ยังไม่มียอดขายรายชั่วโมง",
  "orders": "ออเดอร์",
  "completed orders": "ออเดอร์ที่สำเร็จ",
  "completed cash method": "ออเดอร์เงินสดที่สำเร็จ",
  "completed transfer method": "ออเดอร์โอนเงินที่สำเร็จ",
  "completed pre-orders": "ออเดอร์ก่อนงานที่สำเร็จ",
  "Sold:": "ขายแล้ว:",
  "units": "ชิ้น",
  "Queue created -> called/served": "ตั้งแต่รับคิวจนเรียกหรือเริ่มบริการ",
  "Called/served -> completed": "ตั้งแต่เรียกหรือเริ่มบริการจนเสร็จ",
  "Top Seller": "หมวดสินค้าขายดี",
  "Peak Sales Window": "ช่วงขายหนาแน่น",
  "Queue Drop-Off Risk": "ควรตรวจคิวที่ไม่สำเร็จ",
  "Wait Time Risk": "ควรตรวจเวลารอ",
  "Order settings saved": "บันทึกการตั้งค่าแล้ว",
  "Order settings failed": "บันทึกการตั้งค่าไม่สำเร็จ",
  "Event day": "วันงาน",
  "Open the live workspace when staff is ready": "เมื่อทีมพร้อม เริ่มจัดการหน้าบูธได้เลย",
  "Queue and POS are available for booth operations. Open the booth from Live Queue when sales begin.": "เปิดบูธจากหน้าจัดการคิว แล้วเริ่มรับคิวและขายสินค้าได้",
  "Open Live Queue": "เปิดหน้าจัดการคิว",
  "Open Live POS": "เปิดหน้าขายหน้าบูธ",
  "Open pickup": "ตรวจรายการรับสินค้า",
  "Open Pre-order": "ดูออเดอร์ก่อนงาน",
  "Open Post-order": "ดูออเดอร์หลังงาน",
  "Open Dashboard": "ดูยอดขาย",
  "Booth is closed": "บูธยังปิดอยู่",
  "Open the booth from Live Queue when staff starts accepting walk-ins.": "เมื่อทีมพร้อมรับลูกค้า ให้เปิดบูธจากหน้าจัดการคิว",
  "Done": "ครบแล้ว",
  "Later": "ภายหลัง",
  "Live Booth": "ขายหน้าบูธ",
  "Queue and POS standby": "พร้อมเข้าหน้าคิวและขายสินค้า",
  "Pickup / Post-order": "รับสินค้า / หลังงาน",
  "No pickup action waiting": "ไม่มีรายการรอรับสินค้า",
  "Review": "ดูผลการขาย",
  "Optional for this event": "เลือกเปิดใช้ได้",
  "Pre-order window is configured": "ตั้งช่วงสั่งก่อนงานแล้ว",
  "Post-order window is configured": "ตั้งช่วงสั่งหลังงานแล้ว",
  "Event catalog still needs products": "ยังไม่ได้เลือกสินค้าเข้าร่วมงาน",
  "Booth is open": "บูธเปิดอยู่",
  "Ended / records": "จบงาน / ดูประวัติ",
  "Pre-order open": "เปิดสั่งก่อนงาน",
  "Post-order open": "เปิดสั่งหลังงาน",
  "Needs staff attention": "รายการรอทีมงาน",
  "Clear pickup confirmations first so customer handoff stays accurate.": "ตรวจและยืนยันรายการรับสินค้า เพื่อส่งมอบให้ตรงคนและตรงออเดอร์",
  "Setup required": "ยังต้องตั้งค่า",
  "Choose products for this event": "เลือกสินค้าที่จะขายในงานนี้",
  "No event catalog is selling yet. Add products and event stock before opening sales.": "ยังไม่มีสินค้าที่เปิดขายในงาน เพิ่มสินค้าและจัดสรรสต็อกก่อนเริ่มขาย",
  "Set up Event Catalog": "เลือกสินค้าและสต็อก",
  "Pre-order is open": "กำลังรับออเดอร์ก่อนงาน",
  "Monitor pre-order payments and pickup demand": "ตรวจการชำระเงินและเตรียมส่งมอบออเดอร์ก่อนงาน",
  "Use the order dashboard to confirm transfers, export totals, and prepare fulfillment.": "ตรวจยอดโอน สรุปออเดอร์ และเตรียมสินค้าให้ลูกค้ามารับ",
  "Post-order is open": "กำลังรับออเดอร์หลังงาน",
  "Monitor post-event orders and fulfillment": "ตรวจออเดอร์หลังงานและเตรียมส่งมอบ",
  "Use the post-order dashboard to confirm payments, collect shipping details, and prepare fulfillment.": "ตรวจการชำระเงินและรายละเอียดการรับสินค้าในหน้าออเดอร์หลังงาน",
  "Booth is live": "บูธเปิดขายอยู่",
  "Keep checkout moving": "รับลูกค้าและขายสินค้าได้เลย",
  "POS is ready for walk-in sales. Queue is currently clear.": "ไม่มีคิวรอ เปิดหน้าขายเพื่อรับลูกค้าหน้าบูธได้",
  "Review mode": "ดูผลหลังจบงาน",
  "Review revenue and order records": "ตรวจยอดขายและรายการย้อนหลัง",
  "Preparation": "เตรียมงาน",
  "Review setup before sales open": "ตรวจการตั้งค่าก่อนเปิดขาย",
  "Confirm the event details, catalog, promotions, and pre-order settings before customers arrive.": "ตรวจข้อมูลงาน สินค้า โปรโมชัน และช่วงรับออเดอร์ให้เรียบร้อย",
  "Event is marked cancelled": "อีเวนต์นี้ถูกยกเลิก",
  "Review settings before sharing links or opening sales.": "ตรวจการตั้งค่าก่อนแชร์ลิงก์หรือเปิดขาย",
  "Event Catalog is empty": "ยังไม่มีสินค้าในงาน",
  "Add products to this event before customers can buy.": "เพิ่มสินค้าในงานเพื่อให้ลูกค้าสั่งซื้อได้",
  "Pre-order window is incomplete": "ตั้งช่วงสั่งก่อนงานยังไม่ครบ",
  "Set open and close times so customer ordering follows the intended schedule.": "ตั้งเวลาเปิดและปิดให้ลูกค้าสั่งซื้อได้ตามช่วงที่ต้องการ",
  "Post-order window is incomplete": "ตั้งช่วงสั่งหลังงานยังไม่ครบ",
  "Set open and close times so post-event customer ordering follows the intended schedule.": "ตั้งเวลาเริ่มและปิดรับออเดอร์หลังงาน",
  "Pickup confirmations are waiting": "มีรายการรอยืนยันรับสินค้า",
  "Event Catalog Setup": "เลือกสินค้าและสต็อกของงาน",
  "Choose which library products sell in this event, then set event price and event stock.": "เปิดขายสินค้าที่ต้องการ แล้วกดเพิ่มสต็อกเพื่อจัดสรรจากคลังร้านมาขายในงานนี้ หากยังไม่มีสินค้า ให้เพิ่มในหน้าสินค้าของร้านก่อน",
  "Select event catalog": "เลือกอีเวนต์",
  "No confirmed events": "ยังไม่มีงานที่ยืนยันแล้ว",
  "Event currency": "สกุลเงินของงาน",
  "Select event currency": "เลือกสกุลเงินของงาน",
  "Use product currency": "ใช้สกุลเงินของสินค้า",
  "Search event products...": "ค้นหาสินค้าในงาน...",
  "Filter event catalog category": "กรองหมวดหมู่สินค้าในงาน",
  "Filter event catalog tag": "กรองแท็กสินค้าในงาน",
  "Show": "แสดง",
  "of": "จาก",
  "Bulk actions for visible rows": "จัดการรายการที่กรองอยู่พร้อมกัน",
  "Uses current search and filters": "มีผลกับรายการตามการค้นหาและตัวกรองปัจจุบัน",
  "Sell visible": "เปิดขายที่แสดง",
  "Hide visible": "ซ่อนที่แสดง",
  "Reset visible prices": "คืนราคาที่แสดง",
  "Create or confirm an event before assigning products.": "สร้างและยืนยันอีเวนต์ก่อนเลือกสินค้า",
  "No image": "ยังไม่มีรูป",
  "Custom": "ราคาเฉพาะงาน",
  "Max": "สูงสุด",
  "available for this event.": "ชิ้นที่จัดสรรให้งานนี้ได้",
  "Event price": "ราคาในงาน",
  "Event stock": "สต็อกของงาน",
  "Unlimited": "ไม่จำกัด",
  "Add stock": "เพิ่มสต็อก",
  "Save first to move stock.": "บันทึกสินค้าก่อนเพิ่มหรือคืนสต็อก",
  "Sell / Price": "เปิดขาย / ราคา",
  "Central to event": "คลังร้าน → งานนี้",
  "Actions": "จัดการ",
  "Sell": "เปิดขาย",
  "Save first": "บันทึกก่อน",
  "Unsaved event catalog": "มีการแก้ไขที่ยังไม่บันทึก",
  "Save before using POS or sharing the customer menu for this event.": "บันทึกก่อนเริ่มขายหรือแชร์หน้าร้านให้ลูกค้า",
  "Save catalog": "บันทึกสินค้าในงาน",
  "Overrides": "ราคาเฉพาะงาน",
  "Stock warnings": "สต็อกต้องตรวจ",
  "Unsaved": "ยังไม่บันทึก",
  "Saved": "บันทึกแล้ว",
  "Saved setup is ready for POS and customer menu.": "ใช้ข้อมูลที่บันทึกแล้วในหน้าขายและหน้าร้านลูกค้า",
  "Save changes": "บันทึกการแก้ไข",
  "All categories": "ทุกหมวดหมู่",
  "All tags": "ทุกแท็ก",
  "All": "ทั้งหมด",
  "Hidden": "ซ่อนอยู่",
  "Visual": "แบบรูปภาพ",
  "Operations": "แบบตาราง",
  "Central": "คลังร้าน",
  "Sold/held": "ขายแล้ว / จอง",
  "No products match the current filters.": "ไม่พบสินค้าตามตัวกรอง",
  "No products yet.": "ยังไม่มีสินค้า",
  "No slips waiting for review — all caught up.": "ตรวจสลิปครบแล้ว ไม่มีรายการรอตรวจ",
  "Nothing waiting to ship.": "ไม่มีรายการรอจัดส่ง",
  "No orders match this view.": "ไม่พบออเดอร์ตามตัวกรอง",
  "Opening…": "กำลังเปิด…",
  "Slip": "ดูสลิป",
  "Confirm transfer received?": "ยืนยันว่าได้รับเงินโอนแล้ว?",
  "Mark order shipped?": "ยืนยันว่าจัดส่งสินค้าแล้ว?",
  "Reject payment?": "ยืนยันไม่รับสลิปนี้?",
  "Confirm transfer received": "ยืนยันได้รับเงิน",
  "Reject payment": "ไม่รับสลิป",
  "Payment confirmed": "ยืนยันชำระเงินแล้ว",
  "Payment rejected": "ไม่รับสลิปแล้ว",
  "Reject reason required": "กรุณาระบุเหตุผล",
  "Tracking number required": "กรุณาระบุเลขติดตามพัสดุ",
  "Order marked shipped": "ยืนยันจัดส่งแล้ว",
  "Review failed": "ดำเนินการไม่สำเร็จ",
  "Could not open slip": "เปิดสลิปไม่สำเร็จ",
  "Could not load pre-order dashboard": "โหลดออเดอร์ไม่สำเร็จ",
  "Email still not sent": "ยังส่งอีเมลไม่สำเร็จ",
  "Customer email sent": "ส่งอีเมลให้ลูกค้าแล้ว"
};

export const eventCopy = (language: Language, value: string): string => {
  if (language !== "th") return value;
  if (thai[value]) return thai[value];
  return value
    .replace(/^(\d+) products? selling$/, "เปิดขาย $1 รายการ")
    .replace(/^(\d+) products? available for this event\.$/, "มีสินค้า $1 รายการในงานนี้")
    .replace(/^(\d+\/\d+) finite products? have available stock\.$/, "สินค้าที่มีสต็อกพร้อมขาย $1 รายการ")
    .replace(/^(\d+) awaiting pickup$/, "รอรับสินค้า $1 ออเดอร์")
    .replace(/^(\d+) orders? waiting for pickup$/, "รอรับสินค้า $1 ออเดอร์")
    .replace(/^(\d+) orders? need staff confirmation\.$/, "รอทีมยืนยัน $1 ออเดอร์")
    .replace(/^(\d+) waiting$/, "รออยู่ $1 คิว")
    .replace(/^(\d+) completed orders?/, "ออเดอร์สำเร็จ $1 รายการ")
    .replace(/^(\d+) completed ·/, "สำเร็จ $1 รายการ ·")
    .replace(/^(\d+) completed pre-orders$/, "ออเดอร์ก่อนงานสำเร็จ $1 รายการ")
    .replace(/^(\d+) queue orders$/, "ออเดอร์จากคิว $1 รายการ")
    .replace(/^(\d+) POS orders$/, "ออเดอร์หน้าบูธ $1 รายการ")
    .replace(/^Avg order (.+)$/, "เฉลี่ยต่อออเดอร์ $1")
    .replace(/^from (.+) gross$/, "จากยอดก่อนลด $1")
    .replace(/^(\d+\/\d+) completed$/, "สำเร็จ $1 คิว")
    .replace(/^Expired (\d+) \| Missed (\d+)$/, "หมดอายุ $1 | ไม่มาตามเรียก $2");
};
