-- Keep generated product SKUs short and record whether the seller owns the value.

alter table public.products
  add column if not exists sku_is_generated boolean not null default true;

comment on column public.products.sku_is_generated is
  'True when sku was generated by Nireq; false after a seller supplies or edits it.';

create or replace function public.product_sku_item_code(
  p_name text,
  p_variant_name text
)
returns text
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_name text := upper(coalesce(nullif(trim(p_name), ''), 'ITEM'));
  v_option_source text := upper(coalesce(nullif(trim(p_variant_name), ''), v_name));
  v_tokens text[];
  v_token text;
  v_letters text;
  v_digits text;
  v_item text;
  v_option text := '';
begin
  if v_option_source ~ '(^|[^A-Z0-9])NORMAL([^A-Z0-9]|$)' then
    v_option := 'N';
  elsif v_option_source ~ '(^|[^A-Z0-9])SP([^A-Z0-9]|$)' then
    v_option := 'SP';
  end if;

  select array_agg(part order by ordinal)
  into v_tokens
  from regexp_split_to_table(regexp_replace(v_name, '[^A-Z0-9]+', ' ', 'g'), ' +')
       with ordinality parts(part, ordinal)
  where part <> ''
    and part not in ('CHEKI', 'HAIRCLIP', 'HAIR', 'CLIP', 'PHOTO', 'SET', 'FS', 'HSR', 'NORMAL', 'SP');

  v_token := coalesce(v_tokens[1], 'ITEM');
  if v_token ~ '^[A-Z]{1,3}$' and coalesce(v_tokens[2], '') ~ '^[0-9]+$' then
    v_token := v_token || v_tokens[2];
  end if;
  v_token := coalesce(nullif(regexp_replace(v_token, '[^A-Z0-9]', '', 'g'), ''), 'ITEM');
  v_letters := substring(v_token from '^([A-Z]+)');
  v_digits := substring(v_token from '([0-9]+)$');
  v_item := coalesce(
    nullif(left(coalesce(v_letters, ''), 4) || coalesce(v_digits, ''), ''),
    left(v_token, 8)
  );

  return coalesce(nullif(v_item, ''), 'ITEM')
    || case when v_option = '' then '' else '-' || v_option end;
end;
$$;

create temporary table _compact_product_skus on commit drop as
select
  p.id,
  p.artist_id,
  p.created_at,
  public.product_sku_type_code(p.category, p.name)
    || '-' || public.product_sku_item_code(p.name, p.variant_name) as sku_base,
  coalesce((regexp_match(p.sku, '-([0-9]+)$'))[1]::integer, 0) as old_sequence
from public.products p
where p.deleted_at is null;

update public.products p
set sku = 'MIG-' || replace(p.id::text, '-', ''),
    sku_is_generated = true
where p.deleted_at is null;

do $$
declare
  v_product record;
  v_sequence integer;
  v_candidate text;
begin
  for v_product in
    select * from _compact_product_skus order by artist_id, created_at, id
  loop
    v_sequence := v_product.old_sequence;
    if v_sequence <= 0 then
      select greatest(
        coalesce(max((regexp_match(p.sku, '-([0-9]+)$'))[1]::integer), 0),
        coalesce((
          select max(s.old_sequence)
          from _compact_product_skus s
          where s.artist_id = v_product.artist_id
        ), 0)
      ) + 1
      into v_sequence
      from public.products p
      where p.artist_id = v_product.artist_id
        and p.deleted_at is null
        and p.sku ~ '-[0-9]+$';
    end if;

    v_candidate := v_product.sku_base || '-' || lpad(
      v_sequence::text,
      greatest(3, length(v_sequence::text)),
      '0'
    );
    while exists (
      select 1 from public.products p
      where p.artist_id = v_product.artist_id
        and p.deleted_at is null
        and lower(p.sku) = lower(v_candidate)
        and p.id <> v_product.id
    ) loop
      select greatest(
        coalesce(max((regexp_match(p.sku, '-([0-9]+)$'))[1]::integer), 0),
        coalesce((
          select max(s.old_sequence)
          from _compact_product_skus s
          where s.artist_id = v_product.artist_id
        ), 0)
      ) + 1
      into v_sequence
      from public.products p
      where p.artist_id = v_product.artist_id
        and p.deleted_at is null;
      v_candidate := v_product.sku_base || '-' || lpad(
        v_sequence::text,
        greatest(3, length(v_sequence::text)),
        '0'
      );
    end loop;

    update public.products
    set sku = v_candidate,
        sku_is_generated = true
    where id = v_product.id;
  end loop;
end;
$$;

create or replace function public.generate_product_sku()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_sequence integer;
begin
  if tg_op = 'UPDATE' and new.sku is not distinct from old.sku then
    new.sku_is_generated := old.sku_is_generated;
    return new;
  end if;

  if nullif(trim(coalesce(new.sku, '')), '') is not null then
    new.sku := upper(trim(new.sku));
    new.sku_is_generated := false;
    return new;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(new.artist_id::text, 0));

  select coalesce(max((regexp_match(p.sku, '-([0-9]+)$'))[1]::integer), 0) + 1
  into v_sequence
  from public.products p
  where p.artist_id = new.artist_id
    and p.deleted_at is null
    and p.sku ~ '-[0-9]+$';

  new.sku := public.product_sku_type_code(new.category, new.name)
    || '-' || public.product_sku_item_code(new.name, new.variant_name)
    || '-' || lpad(
      v_sequence::text,
      greatest(3, length(v_sequence::text)),
      '0'
    );
  new.sku_is_generated := true;
  return new;
end;
$$;

comment on function public.generate_product_sku() is
  'Generates a compact editable TYPE-ITEM[-OPTION]-SEQUENCE SKU when blank and records automatic/manual ownership.';
