-- Payment idempotency for POS retries. The key is generated by the client per
-- payment attempt and is used only by SECURITY DEFINER RPCs to make retries
-- return the existing result without creating another completed order or
-- deducting stock twice. It must not be exposed through direct client SELECTs.

alter table public.orders
  add column if not exists payment_idempotency_key uuid;

comment on column public.orders.payment_idempotency_key is
  'Internal POS payment idempotency key. Used only by payment RPCs; do not expose to clients.';

create unique index if not exists orders_payment_idempotency_key_uidx
  on public.orders (payment_idempotency_key)
  where payment_idempotency_key is not null;

-- Existing migrations grant broad table-level SELECT on public.orders. A
-- column-level REVOKE is not enough while table-level SELECT remains granted,
-- so grant direct clients only the columns already used by the app.
revoke select on table public.orders from anon, authenticated;

grant select (
  id,
  created_at,
  event_id,
  queue_id,
  status,
  total_price,
  payment_method,
  currency,
  subtotal_price,
  discount_total,
  pricing_breakdown
) on public.orders to anon, authenticated;

drop function if exists public.create_customer_order_with_stock(uuid, jsonb);
drop function if exists public.create_customer_order_with_stock(uuid, jsonb, uuid);

create or replace function public.create_customer_order_with_stock(
  p_queue_id uuid,
  p_items jsonb,
  p_payment_idempotency_key uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_queue record;
  v_event record;
  v_existing_order record;
  v_item jsonb;
  v_order_id uuid;
  v_product record;
  v_qty integer;
  v_total numeric := 0;
  v_currency text;
  v_available integer;
  v_service_date date;
  v_has_catalog boolean := false;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'empty_items';
  end if;

  select q.* into v_queue
  from public.queues q
  where q.id = p_queue_id
  for update;

  if v_queue.id is null then
    raise exception 'queue_not_found';
  end if;

  if p_payment_idempotency_key is not null then
    select o.id, o.event_id, o.queue_id
    into v_existing_order
    from public.orders o
    where o.payment_idempotency_key = p_payment_idempotency_key
    for update;

    if v_existing_order.id is not null then
      if v_existing_order.event_id = v_queue.event_id
         and v_existing_order.queue_id = v_queue.id then
        return v_existing_order.id;
      end if;
      raise exception 'payment_idempotency_key_conflict';
    end if;
  end if;

  if v_queue.status not in ('waiting', 'calling', 'serving') then
    raise exception 'queue_not_active';
  end if;

  select e.* into v_event
  from public.events e
  where e.id = v_queue.event_id
    and e.artist_id = v_queue.artist_id
    and e.status = 'Confirmed'
    and e.start_date <= now()
    and e.end_date >= now();

  if v_event.id is null then
    raise exception 'event_not_active';
  end if;

  v_service_date := (
    now() at time zone coalesce(nullif(v_event.event_timezone, ''), 'Asia/Bangkok')
  )::date;

  if v_queue.queue_service_date is distinct from v_service_date then
    raise exception 'queue_not_active_today';
  end if;

  select exists (select 1 from public.event_products ep where ep.event_id = v_event.id)
  into v_has_catalog;

  insert into public.orders (event_id, queue_id, status, total_price, currency, payment_method, payment_idempotency_key)
  values (v_event.id, v_queue.id, 'confirmed', 0, 'THB', null, p_payment_idempotency_key)
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, coalesce((v_item ->> 'quantity')::integer, 1));

    select
      p.*,
      ep.id as event_product_id,
      coalesce(ep.price_override, p.price) as effective_price,
      case when ep.id is not null then ep.is_unlimited else p.is_unlimited end as effective_is_unlimited,
      case when ep.id is not null then ep.stock_total else p.stock_total end as effective_stock_total,
      case when ep.id is not null then ep.stock_reserved else p.stock_reserved end as effective_stock_reserved,
      case when ep.id is not null then ep.stock_sold else p.stock_sold end as effective_stock_sold
    into v_product
    from public.products p
    left join public.event_products ep
      on ep.product_id = p.id
     and ep.event_id = v_event.id
    where p.id = (v_item ->> 'product_id')::uuid
      and p.artist_id = v_queue.artist_id
      and p.deleted_at is null
      and p.status = 'enable'
      and (not v_has_catalog or (ep.id is not null and ep.is_enabled = true))
    for update of p;

    if v_product.id is null then
      raise exception 'invalid_product';
    end if;

    if v_currency is null then
      v_currency := v_product.currency;
    elsif v_currency <> v_product.currency then
      raise exception 'mixed_currency_not_allowed';
    end if;

    if not coalesce(v_product.effective_is_unlimited, true) then
      v_available := coalesce(v_product.effective_stock_total, 0) - coalesce(v_product.effective_stock_reserved, 0) - coalesce(v_product.effective_stock_sold, 0);
      if v_available < v_qty then
        raise exception 'insufficient_stock';
      end if;

      if v_product.event_product_id is not null then
        update public.event_products
        set stock_reserved = stock_reserved + v_qty
        where id = v_product.event_product_id;
      else
        update public.products
        set stock_reserved = stock_reserved + v_qty,
            updated_at = now()
        where id = v_product.id;
      end if;
    end if;

    insert into public.order_items (order_id, product_id, event_product_id, quantity, price_per_unit, notes, currency)
    values (
      v_order_id,
      v_product.id,
      v_product.event_product_id,
      v_qty,
      v_product.effective_price,
      coalesce(v_item ->> 'notes', ''),
      v_product.currency
    );

    v_total := v_total + (v_product.effective_price * v_qty);
  end loop;

  update public.orders
  set total_price = v_total,
      subtotal_price = v_total,
      currency = coalesce(v_currency, 'THB')
  where id = v_order_id;

  return v_order_id;
exception
  when unique_violation then
    if p_payment_idempotency_key is not null then
      select o.id, o.event_id, o.queue_id
      into v_existing_order
      from public.orders o
      where o.payment_idempotency_key = p_payment_idempotency_key;

      if v_existing_order.id is not null
         and v_existing_order.event_id = v_queue.event_id
         and v_existing_order.queue_id = v_queue.id then
        return v_existing_order.id;
      end if;
    end if;
    raise;
end;
$$;

grant execute on function public.create_customer_order_with_stock(uuid, jsonb, uuid) to anon, authenticated;

drop function if exists public.sync_customer_order_items_with_stock(uuid, jsonb);
drop function if exists public.sync_customer_order_items_with_stock(uuid, jsonb, uuid);

create or replace function public.sync_customer_order_items_with_stock(
  p_order_id uuid,
  p_items jsonb,
  p_payment_idempotency_key uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order record;
  v_existing_item record;
  v_item jsonb;
  v_product record;
  v_qty integer;
  v_total numeric := 0;
  v_currency text;
  v_available integer;
  v_has_catalog boolean := false;
begin
  if jsonb_typeof(p_items) <> 'array' then
    raise exception 'invalid_items_payload';
  end if;

  if jsonb_array_length(p_items) = 0 then
    raise exception 'empty_items';
  end if;

  select o.*, e.artist_id
  into v_order
  from public.orders o
  join public.events e on e.id = o.event_id
  where o.id = p_order_id
  for update;

  if v_order.id is null then
    raise exception 'order_not_found';
  end if;

  if v_order.queue_id is null then
    raise exception 'order_not_queue_order';
  end if;

  if v_order.status = 'completed' then
    if p_payment_idempotency_key is not null
       and v_order.payment_idempotency_key is not null
       and v_order.payment_idempotency_key <> p_payment_idempotency_key then
      raise exception 'payment_idempotency_key_conflict';
    end if;
    return true;
  end if;

  if v_order.status not in ('draft', 'confirmed') then
    raise exception 'order_not_editable';
  end if;

  if p_payment_idempotency_key is not null
     and v_order.payment_idempotency_key is not null
     and v_order.payment_idempotency_key <> p_payment_idempotency_key then
    raise exception 'payment_idempotency_key_conflict';
  end if;

  if not public.has_artist_role(v_order.artist_id, array['owner', 'queue_pos']) then
    raise exception 'forbidden';
  end if;

  select exists (select 1 from public.event_products ep where ep.event_id = v_order.event_id)
  into v_has_catalog;

  for v_existing_item in
    select oi.product_id, oi.event_product_id, oi.quantity, p.is_unlimited as product_unlimited, ep.is_unlimited as event_unlimited
    from public.order_items oi
    join public.products p on p.id = oi.product_id
    left join public.event_products ep on ep.id = oi.event_product_id
    where oi.order_id = v_order.id
    for update of p
  loop
    if v_existing_item.event_product_id is not null then
      if not coalesce(v_existing_item.event_unlimited, true) then
        update public.event_products
        set stock_reserved = greatest(stock_reserved - v_existing_item.quantity, 0)
        where id = v_existing_item.event_product_id;
      end if;
    elsif not coalesce(v_existing_item.product_unlimited, true) then
      update public.products
      set stock_reserved = greatest(stock_reserved - v_existing_item.quantity, 0),
          updated_at = now()
      where id = v_existing_item.product_id;
    end if;
  end loop;

  delete from public.order_items
  where order_id = v_order.id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, coalesce((v_item ->> 'quantity')::integer, 1));

    select
      p.*,
      ep.id as event_product_id,
      coalesce(ep.price_override, p.price) as effective_price,
      case when ep.id is not null then ep.is_unlimited else p.is_unlimited end as effective_is_unlimited,
      case when ep.id is not null then ep.stock_total else p.stock_total end as effective_stock_total,
      case when ep.id is not null then ep.stock_reserved else p.stock_reserved end as effective_stock_reserved,
      case when ep.id is not null then ep.stock_sold else p.stock_sold end as effective_stock_sold
    into v_product
    from public.products p
    left join public.event_products ep
      on ep.product_id = p.id
     and ep.event_id = v_order.event_id
    where p.id = (v_item ->> 'product_id')::uuid
      and p.artist_id = v_order.artist_id
      and p.deleted_at is null
      and p.status = 'enable'
      and (not v_has_catalog or (ep.id is not null and ep.is_enabled = true))
    for update of p;

    if v_product.id is null then
      raise exception 'invalid_product';
    end if;

    if v_currency is null then
      v_currency := v_product.currency;
    elsif v_currency <> v_product.currency then
      raise exception 'mixed_currency_not_allowed';
    end if;

    if not coalesce(v_product.effective_is_unlimited, true) then
      v_available := coalesce(v_product.effective_stock_total, 0)
        - coalesce(v_product.effective_stock_reserved, 0)
        - coalesce(v_product.effective_stock_sold, 0);

      if v_available < v_qty then
        raise exception 'insufficient_stock';
      end if;

      if v_product.event_product_id is not null then
        update public.event_products
        set stock_reserved = stock_reserved + v_qty
        where id = v_product.event_product_id;
      else
        update public.products
        set stock_reserved = stock_reserved + v_qty,
            updated_at = now()
        where id = v_product.id;
      end if;
    end if;

    insert into public.order_items (order_id, product_id, event_product_id, quantity, price_per_unit, notes, currency)
    values (
      v_order.id,
      v_product.id,
      v_product.event_product_id,
      v_qty,
      v_product.effective_price,
      coalesce(v_item ->> 'notes', ''),
      v_product.currency
    );

    v_total := v_total + (v_product.effective_price * v_qty);
  end loop;

  update public.orders
  set total_price = v_total,
      subtotal_price = v_total,
      currency = coalesce(v_currency, currency, 'THB'),
      status = 'confirmed',
      payment_idempotency_key = coalesce(payment_idempotency_key, p_payment_idempotency_key)
  where id = v_order.id;

  return true;
end;
$$;

grant execute on function public.sync_customer_order_items_with_stock(uuid, jsonb, uuid) to authenticated;

drop function if exists public.complete_order_with_stock(uuid, text);
drop function if exists public.complete_order_with_stock(uuid, text, uuid);

create or replace function public.complete_order_with_stock(
  p_order_id uuid,
  p_payment_method text,
  p_payment_idempotency_key uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order record;
  v_item record;
  v_reserved integer;
  v_missing integer;
  v_unreserved_available integer;
begin
  select o.* into v_order
  from public.orders o
  where o.id = p_order_id
  for update;

  if v_order.id is null then
    raise exception 'order_not_found';
  end if;

  if v_order.status = 'completed' then
    if p_payment_idempotency_key is not null
       and v_order.payment_idempotency_key is not null
       and v_order.payment_idempotency_key <> p_payment_idempotency_key then
      raise exception 'payment_idempotency_key_conflict';
    end if;

    if p_payment_idempotency_key is not null and v_order.payment_idempotency_key is null then
      update public.orders
      set payment_idempotency_key = p_payment_idempotency_key
      where id = v_order.id;
    end if;

    return true;
  end if;

  if v_order.status = 'cancelled' then
    raise exception 'order_cancelled';
  end if;

  if p_payment_idempotency_key is not null
     and v_order.payment_idempotency_key is not null
     and v_order.payment_idempotency_key <> p_payment_idempotency_key then
    raise exception 'payment_idempotency_key_conflict';
  end if;

  for v_item in
    select
      oi.product_id,
      oi.event_product_id,
      oi.quantity,
      p.is_unlimited as product_unlimited,
      p.stock_reserved as product_reserved,
      p.stock_sold as product_sold,
      p.stock_total as product_total,
      ep.is_unlimited as event_unlimited,
      ep.stock_reserved as event_reserved,
      ep.stock_sold as event_sold,
      ep.stock_total as event_total
    from public.order_items oi
    join public.products p on p.id = oi.product_id
    left join public.event_products ep on ep.id = oi.event_product_id
    where oi.order_id = v_order.id
    for update of p
  loop
    if v_item.event_product_id is not null then
      if coalesce(v_item.event_unlimited, true) then
        continue;
      end if;

      v_reserved := least(coalesce(v_item.event_reserved, 0), v_item.quantity);
      v_missing := v_item.quantity - v_reserved;
      v_unreserved_available := coalesce(v_item.event_total, 0) - coalesce(v_item.event_sold, 0) - coalesce(v_item.event_reserved, 0);

      if v_missing > v_unreserved_available then
        raise exception 'insufficient_stock_on_complete';
      end if;

      update public.event_products
      set stock_reserved = greatest(stock_reserved - v_reserved, 0),
          stock_sold = stock_sold + v_item.quantity
      where id = v_item.event_product_id;
    elsif not coalesce(v_item.product_unlimited, true) then
      v_reserved := least(coalesce(v_item.product_reserved, 0), v_item.quantity);
      v_missing := v_item.quantity - v_reserved;
      v_unreserved_available := coalesce(v_item.product_total, 0) - coalesce(v_item.product_sold, 0) - coalesce(v_item.product_reserved, 0);

      if v_missing > v_unreserved_available then
        raise exception 'insufficient_stock_on_complete';
      end if;

      update public.products
      set stock_reserved = greatest(stock_reserved - v_reserved, 0),
          stock_sold = stock_sold + v_item.quantity,
          updated_at = now()
      where id = v_item.product_id;
    end if;
  end loop;

  update public.orders
  set status = 'completed',
      payment_method = p_payment_method,
      payment_idempotency_key = coalesce(payment_idempotency_key, p_payment_idempotency_key)
  where id = v_order.id;

  if v_order.queue_id is not null then
    update public.queues
    set status = 'complete',
        completed_at = now(),
        last_updated_at = now()
    where id = v_order.queue_id;
  end if;

  return true;
end;
$$;

grant execute on function public.complete_order_with_stock(uuid, text, uuid) to authenticated;

drop function if exists public.create_walkin_order_with_stock(uuid, jsonb, text);
drop function if exists public.create_walkin_order_with_stock(uuid, jsonb, text, uuid);

create or replace function public.create_walkin_order_with_stock(
  p_event_id uuid,
  p_items jsonb,
  p_payment_method text,
  p_payment_idempotency_key uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event record;
  v_existing_order record;
  v_item jsonb;
  v_order_id uuid;
  v_product record;
  v_qty integer;
  v_total numeric := 0;
  v_currency text;
  v_available integer;
  v_has_catalog boolean := false;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'empty_items';
  end if;

  select e.* into v_event
  from public.events e
  where e.id = p_event_id;

  if v_event.id is null then
    raise exception 'event_not_active';
  end if;

  if not public.has_artist_role(v_event.artist_id, array['owner', 'queue_pos']) then
    raise exception 'forbidden';
  end if;

  if p_payment_idempotency_key is not null then
    select o.id, o.event_id, o.queue_id
    into v_existing_order
    from public.orders o
    where o.payment_idempotency_key = p_payment_idempotency_key
    for update;

    if v_existing_order.id is not null then
      if v_existing_order.event_id = p_event_id
         and v_existing_order.queue_id is null then
        return v_existing_order.id;
      end if;
      raise exception 'payment_idempotency_key_conflict';
    end if;
  end if;

  if v_event.status <> 'Confirmed'
     or v_event.start_date > now()
     or v_event.end_date < now() then
    raise exception 'event_not_active';
  end if;

  select exists (select 1 from public.event_products ep where ep.event_id = v_event.id)
  into v_has_catalog;

  insert into public.orders (event_id, queue_id, status, total_price, currency, payment_method, payment_idempotency_key)
  values (p_event_id, null, 'completed', 0, 'THB', p_payment_method, p_payment_idempotency_key)
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, coalesce((v_item ->> 'quantity')::integer, 1));

    select
      p.*,
      ep.id as event_product_id,
      coalesce(ep.price_override, p.price) as effective_price,
      case when ep.id is not null then ep.is_unlimited else p.is_unlimited end as effective_is_unlimited,
      case when ep.id is not null then ep.stock_total else p.stock_total end as effective_stock_total,
      case when ep.id is not null then ep.stock_reserved else p.stock_reserved end as effective_stock_reserved,
      case when ep.id is not null then ep.stock_sold else p.stock_sold end as effective_stock_sold
    into v_product
    from public.products p
    left join public.event_products ep
      on ep.product_id = p.id
     and ep.event_id = v_event.id
    where p.id = (v_item ->> 'product_id')::uuid
      and p.artist_id = v_event.artist_id
      and p.deleted_at is null
      and p.status = 'enable'
      and (not v_has_catalog or (ep.id is not null and ep.is_enabled = true))
    for update of p;

    if v_product.id is null then
      raise exception 'invalid_product';
    end if;

    if v_currency is null then
      v_currency := v_product.currency;
    elsif v_currency <> v_product.currency then
      raise exception 'mixed_currency_not_allowed';
    end if;

    if not coalesce(v_product.effective_is_unlimited, true) then
      v_available := coalesce(v_product.effective_stock_total, 0) - coalesce(v_product.effective_stock_reserved, 0) - coalesce(v_product.effective_stock_sold, 0);
      if v_available < v_qty then
        raise exception 'insufficient_stock';
      end if;

      if v_product.event_product_id is not null then
        update public.event_products
        set stock_sold = stock_sold + v_qty
        where id = v_product.event_product_id;
      else
        update public.products
        set stock_sold = stock_sold + v_qty,
            updated_at = now()
        where id = v_product.id;
      end if;
    end if;

    insert into public.order_items (order_id, product_id, event_product_id, quantity, price_per_unit, notes, currency)
    values (
      v_order_id,
      v_product.id,
      v_product.event_product_id,
      v_qty,
      v_product.effective_price,
      coalesce(v_item ->> 'notes', ''),
      v_product.currency
    );

    v_total := v_total + (v_product.effective_price * v_qty);
  end loop;

  update public.orders
  set total_price = v_total,
      subtotal_price = v_total,
      currency = coalesce(v_currency, 'THB')
  where id = v_order_id;

  return v_order_id;
exception
  when unique_violation then
    if p_payment_idempotency_key is not null then
      select o.id, o.event_id, o.queue_id
      into v_existing_order
      from public.orders o
      where o.payment_idempotency_key = p_payment_idempotency_key;

      if v_existing_order.id is not null
         and v_existing_order.event_id = p_event_id
         and v_existing_order.queue_id is null then
        return v_existing_order.id;
      end if;
    end if;
    raise;
end;
$$;

grant execute on function public.create_walkin_order_with_stock(uuid, jsonb, text, uuid) to authenticated;
