


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."update_last_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.last_updated_at = now();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_last_updated_at_column"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_last_updated_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
    new.last_updated_at = now();
    return new;
end;
$$;


ALTER FUNCTION "public"."update_last_updated_column"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."artists" (
    "id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "slug" "text" NOT NULL,
    "display_name" "text" NOT NULL,
    "bio" "text",
    "x_url" "text",
    "facebook_url" "text",
    "ig_url" "text",
    "tiktok_url" "text",
    "email" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "broadcast_message" "text",
    "image_url" "text",
    CONSTRAINT "slug_format_check" CHECK ((("slug" ~ '^[a-z0-9-]+$'::"text") AND ("char_length"("slug") >= 3) AND ("char_length"("slug") <= 30) AND ("slug" <> ALL (ARRAY['admin'::"text", 'settings'::"text", 'login'::"text", 'menu'::"text"]))))
);


ALTER TABLE "public"."artists" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."events" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "artist_id" "uuid",
    "event_name" "text" NOT NULL,
    "start_date" timestamp with time zone NOT NULL,
    "end_date" timestamp with time zone NOT NULL,
    "location_name" "text",
    "location_detail" "text",
    "transit_info" "text",
    "booth_number" "text",
    "entrance_fee" "text",
    "status" "text" DEFAULT 'Confirmed'::"text",
    "is_next_up" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "last_updated_at" timestamp with time zone DEFAULT "now"(),
    "is_booth_open" boolean DEFAULT false,
    "broadcast_message" "text"
);


ALTER TABLE "public"."events" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "artist_id" "uuid",
    "name" "text" NOT NULL,
    "price" numeric DEFAULT 0,
    "description" "text",
    "category" "text",
    "image_url" "text",
    "is_out_of_stock" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "status" "text" DEFAULT 'enable'::"text",
    CONSTRAINT "products_status_check" CHECK (("status" = ANY (ARRAY['enable'::"text", 'disable'::"text", 'soldout'::"text"])))
);


ALTER TABLE "public"."products" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."queues" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "artist_id" "uuid" NOT NULL,
    "queue_number" integer NOT NULL,
    "status" "text" DEFAULT 'waiting'::"text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "last_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event_id" "uuid",
    "called_at" timestamp with time zone,
    "completed_at" timestamp with time zone,
    "served_at" timestamp with time zone,
    CONSTRAINT "queues_status_check" CHECK (("status" = ANY (ARRAY['waiting'::"text", 'calling'::"text", 'serving'::"text", 'complete'::"text", 'missed'::"text", 'expired'::"text"])))
);

ALTER TABLE ONLY "public"."queues" REPLICA IDENTITY FULL;


ALTER TABLE "public"."queues" OWNER TO "postgres";


ALTER TABLE "public"."queues" ALTER COLUMN "queue_number" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."queues_queue_number_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."artists"
    ADD CONSTRAINT "artists_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."artists"
    ADD CONSTRAINT "artists_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."queues"
    ADD CONSTRAINT "queues_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "idx_artists_slug" ON "public"."artists" USING "btree" ("slug");



CREATE OR REPLACE TRIGGER "set_last_updated" BEFORE UPDATE ON "public"."queues" FOR EACH ROW EXECUTE FUNCTION "public"."update_last_updated_column"();



CREATE OR REPLACE TRIGGER "update_artists_updated_at" BEFORE UPDATE ON "public"."artists" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_events_last_updated_at" BEFORE UPDATE ON "public"."events" FOR EACH ROW EXECUTE FUNCTION "public"."update_last_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_products_updated_at" BEFORE UPDATE ON "public"."products" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_artist_id_fkey" FOREIGN KEY ("artist_id") REFERENCES "public"."artists"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_artist_id_fkey" FOREIGN KEY ("artist_id") REFERENCES "public"."artists"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."queues"
    ADD CONSTRAINT "queues_artist_id_fkey" FOREIGN KEY ("artist_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."queues"
    ADD CONSTRAINT "queues_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id");



CREATE POLICY "Allow artist to update queues" ON "public"."queues" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Allow public read access" ON "public"."events" FOR SELECT USING (true);



CREATE POLICY "Allow public read access for artists" ON "public"."artists" FOR SELECT USING (true);



CREATE POLICY "Allow public read access for events" ON "public"."events" FOR SELECT TO "anon" USING (true);



CREATE POLICY "Allow public to insert queues" ON "public"."queues" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Allow public to join queue" ON "public"."queues" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public to leave queue" ON "public"."queues" FOR UPDATE TO "anon" USING (true) WITH CHECK (("status" = 'missed'::"text"));



CREATE POLICY "Allow public to select queues" ON "public"."queues" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Anyone can insert a queue" ON "public"."queues" FOR INSERT WITH CHECK (true);



CREATE POLICY "Anyone can view queues" ON "public"."queues" FOR SELECT USING (true);



CREATE POLICY "Artist can manage own events" ON "public"."events" USING (("auth"."uid"() = "artist_id"));



CREATE POLICY "Artist can manage own products" ON "public"."products" USING (("auth"."uid"() = "artist_id")) WITH CHECK (("auth"."uid"() = "artist_id"));



CREATE POLICY "Artists can insert their own products" ON "public"."products" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "artist_id"));



CREATE POLICY "Artists full access to own queues" ON "public"."queues" TO "authenticated" USING (("auth"."uid"() = "artist_id")) WITH CHECK (("auth"."uid"() = "artist_id"));



CREATE POLICY "Enable delete for authenticated users only" ON "public"."events" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable insert for public" ON "public"."queues" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."queues" FOR SELECT USING (true);



CREATE POLICY "Enable update for all users" ON "public"."artists" FOR UPDATE TO "authenticated", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "Enable update for artists based on user_id" ON "public"."queues" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "artist_id")) WITH CHECK (("auth"."uid"() = "artist_id"));



CREATE POLICY "Enable update for authenticated users only" ON "public"."events" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Events_Delete_Own" ON "public"."events" FOR DELETE USING (("auth"."uid"() = "artist_id"));



CREATE POLICY "Events_Insert_Own" ON "public"."events" FOR INSERT WITH CHECK (("auth"."uid"() = "artist_id"));



CREATE POLICY "Events_Select_Own" ON "public"."events" FOR SELECT USING (("auth"."uid"() = "artist_id"));



CREATE POLICY "Events_Update_Own" ON "public"."events" FOR UPDATE USING (("auth"."uid"() = "artist_id"));



CREATE POLICY "Everyone can insert queues" ON "public"."queues" FOR INSERT WITH CHECK (true);



CREATE POLICY "Everyone can view queues" ON "public"."queues" FOR SELECT USING (true);



CREATE POLICY "Owner_Update_Artist" ON "public"."artists" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "id")) WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Public can view active events" ON "public"."events" FOR SELECT USING (true);



CREATE POLICY "Public can view artists" ON "public"."artists" FOR SELECT USING (true);



CREATE POLICY "Public can view products" ON "public"."products" FOR SELECT USING (true);



ALTER TABLE "public"."artists" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."queues" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."artists";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."events";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."products";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."queues";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."update_last_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_last_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_last_updated_at_column"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_last_updated_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_last_updated_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_last_updated_column"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";


















GRANT ALL ON TABLE "public"."artists" TO "anon";
GRANT ALL ON TABLE "public"."artists" TO "authenticated";
GRANT ALL ON TABLE "public"."artists" TO "service_role";



GRANT ALL ON TABLE "public"."events" TO "anon";
GRANT ALL ON TABLE "public"."events" TO "authenticated";
GRANT ALL ON TABLE "public"."events" TO "service_role";



GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";



GRANT ALL ON TABLE "public"."queues" TO "anon";
GRANT ALL ON TABLE "public"."queues" TO "authenticated";
GRANT ALL ON TABLE "public"."queues" TO "service_role";



GRANT ALL ON SEQUENCE "public"."queues_queue_number_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."queues_queue_number_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."queues_queue_number_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

drop policy "Enable update for all users" on "public"."artists";

drop policy "Allow public to insert queues" on "public"."queues";

drop policy "Allow public to select queues" on "public"."queues";


  create policy "Enable update for all users"
  on "public"."artists"
  as permissive
  for update
  to anon, authenticated
using (true)
with check (true);



  create policy "Allow public to insert queues"
  on "public"."queues"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "Allow public to select queues"
  on "public"."queues"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "Artists can upload menu images"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'Menu'::text));



  create policy "Artists_Manage_Avatars"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using (((bucket_id = 'Avatar'::text) AND (name ~~ (auth.uid() || '/%'::text))))
with check (((bucket_id = 'Avatar'::text) AND (name ~~ (auth.uid() || '/%'::text))));



  create policy "Display Image Menu 1fblr_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'Menu'::text) AND ((storage.foldername(name))[1] = 'public'::text)));



  create policy "Give access to a file to user 1fblr_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'Menu'::text) AND (name ~~ (('admin/assets/'::text || (auth.uid())::text) || '/%'::text))));



  create policy "Give access to a file to user 1fblr_1"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'Menu'::text) AND (name ~~ (('admin/assets/'::text || (auth.uid())::text) || '/%'::text))));



  create policy "Give access to a file to user 1fblr_2"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'Menu'::text) AND (name ~~ (('admin/assets/'::text || (auth.uid())::text) || '/%'::text))));



  create policy "Give access to a file to user 1fblr_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'Menu'::text) AND (name ~~ (('admin/assets/'::text || (auth.uid())::text) || '/%'::text))));



  create policy "Give anon users access to JPG images in folder 1fblr_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'Menu'::text) AND (lower(storage.extension(name)) = ANY (ARRAY['jpg'::text, 'jpeg'::text, 'png'::text])) AND (lower((storage.foldername(name))[1]) = 'public'::text)));



  create policy "Public_View_Avatars"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'Avatar'::text));



